name: dapp_flutter_imane
description: A simple HelloWorld DApp linking Flutter with an Ethereum contract.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  web3dart: ^2.5.0
  http: ^0.13.6
  web_socket_channel: ^2.2.0


flutter:
  assets:
    - src/artifacts/HelloWorld.json
